#!/usr/bin/env python3
"""Generate a runnable MuJoCo scene from the read-only wbc_h12 robot model.

``wbc_h12``'s ``mjcf/h2_edu.xml`` cannot be loaded as-is for physics:

* its ``<compiler meshdir="meshes/">`` resolves next to the MJCF, but the STL
  files live under ``urdf/h2_edu/meshes`` -- inside ``wbc_h12``, ``motion_lib``
  only ever parses this file as XML, so the gap never surfaces there;
* it declares no ground plane, no light and no ``<option>``, because it exists to
  provide forward-kinematics offsets rather than a simulation;
* its joints carry no ``armature`` and its motors no ``ctrlrange``. Isaac Lab
  supplies both from the actuator configs, and without the rotor inertia the
  policy's stiffnesses (up to kp=99 on the legs) diverge into NaN within a few
  seconds at a 5 ms timestep.

Rather than patch ``wbc_h12`` (which must stay byte-identical for upstream
swaps), this writes a new scene into ``Mujoco/assets/`` that points ``meshdir`` at
the read-only mesh directory and adds the missing scene furniture, rotor inertia
and torque limits.

    python tools/make_scene.py
    python tools/make_scene.py --wbc-root /opt/wbc_h12 --out assets/h2_edu_scene.xml
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, "/opt")  # h2_policy_if is mounted there, read-only
from h2_policy_if import evaluation as h2_evaluation, h2_joints  # noqa: E402

# sim.dt from gear_sonic/envs/manager_env/modular_tracking_env_cfg.py:969.
PHYSICS_TIMESTEP = 0.005
NUM_DOF = h2_joints.NUM_DOF


def build_scene(mjcf_path: Path, mesh_dir: Path, timestep: float) -> ET.ElementTree:
    """Load the robot MJCF and add everything a physics scene needs.

    Args:
        mjcf_path: ``mjcf/h2_edu.xml`` inside the read-only checkout.
        mesh_dir: Directory holding the robot's STL files.
        timestep: Physics timestep [s].

    Returns:
        The modified tree, ready to write.

    Raises:
        SystemExit: If the asset is not the 31-DOF floating-base model this
            expects, which would make the generated scene silently wrong.
    """
    tree = ET.parse(mjcf_path)
    root = tree.getroot()

    hinges = [j for j in root.iter("joint") if j.get("type") != "free"]
    frees = [j for j in root.iter("joint") if j.get("type") == "free"]
    if len(hinges) != NUM_DOF:
        raise SystemExit(f"{mjcf_path} has {len(hinges)} hinge joints, expected {NUM_DOF}")
    if not frees:
        raise SystemExit(
            f"{mjcf_path} has no free joint, so the robot would be welded to the world. "
            "The EDU URDF keeps its floating base commented out for Isaac Lab; the MJCF "
            "generated by h2_tools/retargeting/make_h2edu_mjcf.py is supposed to enable it."
        )

    # Rotor inertia and torque saturation, which Isaac Lab applies through its
    # actuator configs and this asset therefore omits. Indexed by joint name so a
    # reordered upstream asset cannot silently misassign them.
    armature = dict(zip(h2_joints.JOINT_NAMES_MUJOCO, h2_joints.ARMATURE_MUJOCO))
    effort = dict(zip(h2_joints.JOINT_NAMES_MUJOCO, h2_joints.EFFORT_LIMIT_MUJOCO))
    for joint in hinges:
        name = joint.get("name")
        if name not in armature:
            raise SystemExit(
                f"{mjcf_path} declares joint {name!r}, which h2_policy_if/h2_joints.py does not "
                "know. Run h2_policy_server/tools/verify_constants.py."
            )
        joint.set("armature", f"{armature[name]:.9f}")

    for motor in root.iter("motor"):
        joint_name = motor.get("joint")
        if joint_name not in effort:
            raise SystemExit(f"{mjcf_path} has a motor on unknown joint {joint_name!r}")
        limit = effort[joint_name]
        motor.set("ctrlrange", f"{-limit:g} {limit:g}")
        motor.set("ctrllimited", "true")

    compiler = root.find("compiler")
    if compiler is None:
        compiler = ET.SubElement(root, "compiler")
    # Absolute, so the scene is loadable from any working directory.
    compiler.set("meshdir", str(mesh_dir))

    option = root.find("option")
    if option is None:
        option = ET.Element("option")
        root.insert(0, option)
    option.set("timestep", str(timestep))

    worldbody = root.find("worldbody")
    if worldbody is None:
        raise SystemExit(f"{mjcf_path} has no <worldbody>")

    asset = root.find("asset")
    if asset is None:
        asset = ET.SubElement(root, "asset")
    ET.SubElement(
        asset,
        "texture",
        name="groundplane",
        type="2d",
        builtin="checker",
        rgb1="0.2 0.3 0.4",
        rgb2="0.1 0.2 0.3",
        width="300",
        height="300",
    )
    ET.SubElement(
        asset, "material", name="groundplane", texture="groundplane", texrepeat="5 5", reflectance="0.1"
    )

    # Prepended so the floor and light come before the robot body, which keeps the
    # free joint's qpos at indices 0..6 -- sim code slices d.qpos[7:] for joints.
    light = ET.Element("light", pos="0 0 4", dir="0 0 -1", directional="true")
    # Friction comes from the training terrain material, not from MuJoCo's
    # defaults: static_friction = dynamic_friction = 1.0
    # (modular_tracking_env_cfg.py:345-346). MuJoCo's `friction` triple is
    # (sliding, torsional, rolling) with a single sliding coefficient, whereas
    # PhysX carries static and dynamic separately -- they coincide at 1.0 here,
    # so the sliding term maps exactly and no static/dynamic distinction is lost.
    # The torsional and rolling terms have no PhysX counterpart in the training
    # config; MuJoCo's defaults (0.005, 0.0001) are kept and recorded as an
    # approximation in the run's provenance.
    sliding = h2_evaluation.TERRAIN_MATERIAL["static_friction"].value
    floor = ET.Element(
        "geom",
        name="floor",
        type="plane",
        size="0 0 0.05",
        material="groundplane",
        # condim 3 = sliding friction only, which matches a PhysX material that
        # declares no torsional or rolling friction.
        condim="3",
        friction=f"{sliding} 0.005 0.0001",
        solref="0.02 1",
        solimp="0.9 0.95 0.001",
    )
    worldbody.insert(0, floor)
    worldbody.insert(0, light)

    if root.find("statistic") is None:
        ET.SubElement(root, "statistic", center="0 0 0.7", extent="2.0")
    return tree


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--wbc-root",
        type=Path,
        default=Path("/opt/wbc_h12"),
        help="read-only wbc_h12 checkout",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "assets" / "h2_edu_scene.xml",
        help="generated scene path",
    )
    parser.add_argument("--timestep", type=float, default=PHYSICS_TIMESTEP)
    args = parser.parse_args()

    robot_desc = args.wbc_root / "gear_sonic/data/assets/robot_description"
    mjcf_path = robot_desc / "mjcf/h2_edu.xml"
    mesh_dir = robot_desc / "urdf/h2_edu/meshes"
    for path in (mjcf_path, mesh_dir):
        if not path.exists():
            raise SystemExit(f"{path} not found. Is --wbc-root right, and was `git lfs pull` run?")

    stl = sorted(mesh_dir.glob("*.stl"))
    if not stl:
        raise SystemExit(f"no STL files in {mesh_dir}")
    if stl[0].stat().st_size < 10_000:
        raise SystemExit(
            f"{stl[0]} is {stl[0].stat().st_size} bytes -- these are Git LFS pointers.\n"
            f"Run: (cd {args.wbc_root} && git lfs pull)"
        )

    tree = build_scene(mjcf_path, mesh_dir, args.timestep)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(tree, space="  ")
    tree.write(args.out, encoding="unicode", xml_declaration=False)
    print(f"wrote {args.out}")
    print(f"  meshdir  {mesh_dir}")
    print(f"  timestep {args.timestep}")
    print(f"  armature {h2_joints.ARMATURE_MUJOCO.min():.6f}..{h2_joints.ARMATURE_MUJOCO.max():.6f} kg m^2")
    print(f"  torque   {h2_joints.EFFORT_LIMIT_MUJOCO.min():g}..{h2_joints.EFFORT_LIMIT_MUJOCO.max():g} N m")

    try:
        import mujoco
    except ImportError:
        print("  (mujoco not importable here; skipping the load check)")
        return
    model = mujoco.MjModel.from_xml_path(str(args.out))
    print(
        f"  loaded   nq={model.nq} nv={model.nv} nu={model.nu} "
        f"nbody={model.nbody} njnt={model.njnt}"
    )
    if model.nq != 7 + NUM_DOF:
        print(f"  WARNING nq is {model.nq}, expected {7 + NUM_DOF}", file=sys.stderr)


if __name__ == "__main__":
    main()
